# Generated by Django 3.1.7 on 2022-01-20 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0004_auto_20211023_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsAppointmentModel',
            fields=[
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='smsappointmentmodel', serialize=False, to='department.employee')),
                ('step', models.IntegerField(default=0)),
                ('date_chosen', models.DateField(blank=True, null=True)),
                ('time_chosen', models.TimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancel_reason', models.CharField(blank=True, max_length=512, null=True)),
                ('reason', models.CharField(choices=[('1', 'Schedule'), ('2', 'Cancel')], default='2', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SmsAppointmentModelConfirm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_chosen', models.DateField(blank=True, null=True)),
                ('time_chosen', models.TimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancel_reason', models.CharField(blank=True, max_length=512, null=True)),
                ('reason', models.CharField(choices=[('1', 'Schedule'), ('2', 'Cancel')], default='2', max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmedsmsappointments', to='department.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(max_length=100)),
                ('appointment_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='sms.smsappointmentmodel')),
            ],
        ),
    ]
