# Generated by Django 3.1.7 on 2021-08-07 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='day',
            old_name='start_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='end_date',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='start_date',
            new_name='start_time',
        ),
    ]
